---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lease2fip-hcloud
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lease2fip-hcloud
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lease2fip-hcloud
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lease2fip-hcloud
subjects:
- kind: ServiceAccount
  name: lease2fip-hcloud
