name: build

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  CONTAINER_IMAGE_NAME: ghcr.io/hcloud/lease2fip-hcloud

jobs:
  package-platform-specific-container-image:
    strategy:
      matrix:
        runner:
        - ubuntu-24.04
#        - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
    - id: platform
      name: Generate platform
      run: |
        case "${{ matrix.runner }}" in
          "ubuntu-24.04")
            echo "PLATFORM=linux/amd64" >> $GITHUB_ENV
            ;;
          "ubuntu-24.04-arm")
            echo "PLATFORM=linux/arm64" >> $GITHUB_ENV
            ;;
          *)
            echo "Unsupported runner: ${{ matrix.runner }}"
            exit 1
            ;;
        esac
    - id: metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.CONTAINER_IMAGE_NAME }}
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        build-args: |
          GIT_COMMIT_HASH=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        labels: ${{ steps.metadata.outputs.labels }}
        outputs: type=image,push-by-digest=true,name-canonical=true,push=false
        platforms: ${{ steps.platform.outputs.PLATFORM }}
        tags: ${{ env.CONTAINER_IMAGE_NAME }}:commit-${{ github.sha }}
